name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build and Test']                
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1.9.1
      with:
        artifact: test-results            # artifact name
        name: Unit Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
