name: Static Code Analysis and Security Testing

on:
  workflow_run:
    workflows: ['Build and Test']  
    types:
      - completed

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_version: 1.23.7

      - name: Run Detekt
        run: |
          detekt-cli \
          --input app/src/main \
          --report xml:detekt-report.xml \
          --report html:detekt-report.html \
          --build-upon-default-config

      - name: Upload Detekt Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: detekt-reports
          path: |
            detekt-report.xml
            detekt-report.html

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'MyAndroidApp'
          path: '.'
          format: 'ALL'
          out: 'dependency-check-reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload OWASP Dependency-Check Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-reports
          path: dependency-check-reports
