name: Static Code Analysis and Security Testing

on:
  workflow_run:
    workflows: ['Build and Test']  
    types:
      - completed

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Detekt CLI
        run: |
          DETEKT_VERSION=$(curl -s https://api.github.com/repos/detekt/detekt/releases/latest | grep 'tag_name' | cut -d'"' -f4)
          curl -sSfL "https://github.com/detekt/detekt/releases/download/$DETEKT_VERSION/detekt-cli-all-$DETEKT_VERSION.jar" -o detekt-cli.jar

      - name: Run Detekt
        run: |
          java -jar detekt-cli.jar \
          --input app/src/main \
          --report xml:detekt-report.xml \
          --report html:detekt-report.html \
          --build-upon-default-config

      - name: Upload Detekt Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: detekt-reports
          path: |
            detekt-report.xml
            detekt-report.html

  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OWASP Dependency-Check
        run: |
          DEPENDENCY_CHECK_VERSION=$(curl -s https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest | grep 'tag_name' | cut -d'"' -f4)
          curl -sSfL "https://github.com/jeremylong/DependencyCheck/releases/download/$DEPENDENCY_CHECK_VERSION/dependency-check-$DEPENDENCY_CHECK_VERSION-release.zip" -o dependency-check.zip
          unzip dependency-check.zip -d dependency-check

      - name: Run OWASP Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
          --project MyAndroidApp \
          --scan . \
          --out ./dependency-check-report \
          --format ALL

      - name: Upload OWASP Dependency-Check Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-reports
          path: ./dependency-check-report
